// routes/index.js (final)
const express = require("express");
const router = express.Router();
const supabaseAdmin = require("../supabaseAdmin"); // optional client (may be null)

// ---- Curated fallbacks (unchanged) ----
const FALLBACK = {
  trending: [
    { id: "ol-origin-darwin", provider: "openlibrary", title: "On the Origin of Species", author: "Charles Darwin",
      cover: "https://covers.openlibrary.org/b/olid/OL25442902M-L.jpg",
      href: "/read?provider=openlibrary&id=OL25442902M", subjects: ["Science", "Biology"] },
    { id: "pg-relativity", provider: "gutenberg", title: "Relativity: The Special and General Theory", author: "Albert Einstein",
      cover: "https://www.gutenberg.org/cache/epub/30155/pg30155.cover.medium.jpg",
      href: "/read?provider=gutenberg&id=30155", subjects: ["Science", "Physics"] },
    { id: "ol-benfranklin-autobio", provider: "openlibrary", title: "The Autobiography of Benjamin Franklin", author: "Benjamin Franklin",
      cover: "https://covers.openlibrary.org/b/olid/OL24374150M-L.jpg",
      href: "/read?provider=openlibrary&id=OL24374150M", subjects: ["Biography", "History"] },
    { id: "pg-plato-republic", provider: "gutenberg", title: "The Republic", author: "Plato",
      cover: "https://www.gutenberg.org/cache/epub/1497/pg1497.cover.medium.jpg",
      href: "/read?provider=gutenberg&id=1497", subjects: ["Philosophy"] },
    { id: "ol-opticks-newton", provider: "openlibrary", title: "Opticks", author: "Isaac Newton",
      cover: "https://covers.openlibrary.org/b/olid/OL24263840M-L.jpg",
      href: "/read?provider=openlibrary&id=OL24263840M", subjects: ["Science", "Physics"] },
    { id: "pg-gulliver", provider: "gutenberg", title: "Gulliver’s Travels", author: "Jonathan Swift",
      cover: "https://www.gutenberg.org/cache/epub/829/pg829.cover.medium.jpg",
      href: "/read?provider=gutenberg&id=829", subjects: ["Fiction", "Satire"] },
    { id: "ol-prince-machiavelli", provider: "openlibrary", title: "The Prince", author: "Niccolò Machiavelli",
      cover: "https://covers.openlibrary.org/b/olid/OL27665455M-L.jpg",
      href: "/read?provider=openlibrary&id=OL27665455M", subjects: ["Politics", "History"] },
    { id: "pg-art-of-war", provider: "gutenberg", title: "The Art of War", author: "Sun Tzu",
      cover: "https://www.gutenberg.org/cache/epub/132/pg132.cover.medium.jpg",
      href: "/read?provider=gutenberg&id=132", subjects: ["Strategy", "History"] },
  ],
  philosophy: [
    { id: "pg-ethics", provider: "gutenberg", title: "Ethics", author: "Benedict de Spinoza",
      cover: "https://www.gutenberg.org/cache/epub/3800/pg3800.cover.medium.jpg",
      href: "/read?provider=gutenberg&id=3800", subjects: ["Philosophy"] },
    { id: "pg-zarathustra", provider: "gutenberg", title: "Thus Spoke Zarathustra", author: "Friedrich Nietzsche",
      cover: "https://www.gutenberg.org/cache/epub/1998/pg1998.cover.medium.jpg",
      href: "/read?provider=gutenberg&id=1998", subjects: ["Philosophy"] },
    { id: "pg-utilitarianism", provider: "gutenberg", title: "Utilitarianism", author: "John Stuart Mill",
      cover: "https://www.gutenberg.org/cache/epub/11224/pg11224.cover.medium.jpg",
      href: "/read?provider=gutenberg&id=11224", subjects: ["Philosophy"] },
    { id: "pg-meditations", provider: "gutenberg", title: "Meditations", author: "Marcus Aurelius",
      cover: "https://www.gutenberg.org/cache/epub/2680/pg2680.cover.medium.jpg",
      href: "/read?provider=gutenberg&id=2680", subjects: ["Philosophy","Stoicism"] },
    { id: "pg-republic", provider: "gutenberg", title: "The Republic", author: "Plato",
      cover: "https://www.gutenberg.org/cache/epub/1497/pg1497.cover.medium.jpg",
      href: "/read?provider=gutenberg&id=1497", subjects: ["Philosophy"] },
  ],
  history: [
    { id: "pg-history-herodotus", provider: "gutenberg", title: "The Histories", author: "Herodotus",
      cover: "https://www.gutenberg.org/cache/epub/2707/pg2707.cover.medium.jpg",
      href: "/read?provider=gutenberg&id=2707", subjects: ["History"] },
    { id: "ol-souls-black-folk", provider: "openlibrary", title: "The Souls of Black Folk", author: "W. E. B. Du Bois",
      cover: "https://covers.openlibrary.org/b/olid/OL24378309M-L.jpg",
      href: "/read?provider=openlibrary&id=OL24378309M", subjects: ["History","Sociology"] },
    { id: "pg-decline-fall", provider: "gutenberg", title: "The History of the Decline and Fall of the Roman Empire (Vol. 1)", author: "Edward Gibbon",
      cover: "https://www.gutenberg.org/cache/epub/731/pg731.cover.medium.jpg",
      href: "/read?provider=gutenberg&id=731", subjects: ["History"] },
    { id: "ol-pride-prejudice", provider: "openlibrary", title: "Pride and Prejudice", author: "Jane Austen",
      cover: "https://covers.openlibrary.org/b/olid/OL25428444M-L.jpg",
      href: "/read?provider=openlibrary&id=OL25428444M", subjects: ["Fiction","History"] },
  ],
  science: [
    { id: "
